# Generated by Django 5.0.1 on 2024-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
        ('videos', '0003_alter_videos_author_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),

    ]
