# Generated by Django 5.0.1 on 2024-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videos_author_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='course',
            field=models.CharField(default='Lesson', max_length=255),
        ),
        migrations.AlterField(
            model_name='videos',
            name='miniature',
            field=models.ImageField(default='videos/static/medias/miniatures/default_image.png', upload_to='videos/static/medias/miniatures/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(upload_to='videos/static/medias/videos/'),
        ),

    ]
