# Generated by Django 5.0.1 on 2024-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videos_course_alter_videos_miniature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='logo',
            field=models.ImageField(default='videos/static/medias/miniatures/default_image.png', upload_to='videos/static/medias/logo/'),
        ),

    ]
