# Generated by Django 5.0.1 on 2024-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videos_logo_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='course_description',
            field=models.CharField(default='Description', max_length=255),
        ),

    ]
