# Generated by Django 5.0.1 on 2024-02-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_videos_logo_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='logo',
        ),

    ]
