# Generated by Django 5.0.1 on 2024-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_videos_logo_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='logo',
        ),
        migrations.AddField(
            model_name='videos',
            name='logo_url',
            field=models.CharField(default='videos/static/medias/logo/python.png', max_length=50),
        ),

    ]
