# Generated by Django 5.0.1 on 2024-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0013_videos_niveau_delete_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="video_file",
        ),
        migrations.AddField(
            model_name="videos",
            name="youtube_video_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        
    ]
