# Generated by Django 5.0.1 on 2024-03-23 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0014_remove_videos_video_file_videos_youtube_video_id_and_more"),
    ]

    operations = [
        
    ]
