# Generated by Django 5.0.1 on 2024-03-25 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0015_delete_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
