# Generated by Django 5.0.1 on 2024-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="user_image/default_image.png", upload_to="static/user_image/"
            ),
        ),
    ]
